[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
directory = ".netlify/functions-internal"
node_bundler = "esbuild"

[[functions]]
path = "/api/*"
included_files = ["node_modules/**"]

[dev]
command = "npm run dev"
port = 9005
targetPort = 9005
