[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
directory = ".netlify/functions-internal"
node_bundler = "esbuild"
included_files = ["node_modules/sharp/**", "node_modules/pixelmatch/**"]

[dev]
command = "npm run dev"
port = 9005
targetPort = 9005
